### ISSUE TITLE
scheduler policy configuration

### ISSUE THREAD

**Issue by Fizzbb** [CentaurusInfra/alnair#44]
How to easily switch from binpack vs spread out for different jobs.

**Comment by YHDING23** [comment]
To the best of my knowledge, the scheduling policy configuration does not compatible with the scheduling framework anymore. As seen in [Scheduling Policies](https://kubernetes.io/docs/reference/scheduling/policies/). 

Regarding your question about the easy switch, my suggestion is to build two separate scheduling profiles, where users can assign the binpack or spreading policy to their specific Pods/Jobs, accordingly.

**Comment by Fizzbb** [comment]
configMap has all available profiles, pod choose scheduler profile in yaml.
