### ISSUE TITLE
Prometheus targets down

### ISSUE THREAD

**Issue by Fizzbb** [CentaurusInfra/alnair#6]
When Prometheus scrape pods on different nodes, metrics are not collected. "<Prometheus_server_ip>:9090/targets" shows the target (Pod or Endpoint IP) is down. However, connections (curl) between those two pods exist. 

target down reason "context deadlines exceed"

**Comment by CoderKevinZhang** [comment]
the issue is it took around 4s to retrieve the data from one gpu cluster that is located in Santa Clara. Has switched the gpu cluster with Zhaobo and issue fixed.
